//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace OrderIT.ModelIA
{
    [DataContract(IsReference = true)]
    public partial class Customer : Company 
    {
        #region Primitive Properties
    	
        [DataMember]
        public virtual string WSUserName
        {
            get { return _wSUserName; }
            set { _wSUserName = value; NotifyPropertyChanged("WSUserName"); }
        }
        private string _wSUserName;
        protected string WSUserNameEdit { get; set; }
    	
        [DataMember]
        public virtual string WSPassword
        {
            get { return _wSPassword; }
            set { _wSPassword = value; NotifyPropertyChanged("WSPassword"); }
        }
        private string _wSPassword;
        protected string WSPasswordEdit { get; set; }
    	
        [DataMember]
        public virtual Nullable<bool> WSEnabled
        {
            get { return _wSEnabled; }
            set { _wSEnabled = value; NotifyPropertyChanged("WSEnabled"); }
        }
        private Nullable<bool> _wSEnabled;
        protected Nullable<bool> WSEnabledEdit { get; set; }

        #endregion
        #region Complex Properties
    	
        [DataMember]
        public virtual AddressInfo BillingAddress
        {
            get { return _billingAddress; }
            set { _billingAddress = value; NotifyPropertyChanged("BillingAddress"); }
        }
        private AddressInfo _billingAddress = new AddressInfo();
        private AddressInfo _billingAddressEdit = new AddressInfo();
    	
        [DataMember]
        public virtual AddressInfo ShippingAddress
        {
            get { return _shippingAddress; }
            set { _shippingAddress = value; NotifyPropertyChanged("ShippingAddress"); }
        }
        private AddressInfo _shippingAddress = new AddressInfo();
        private AddressInfo _shippingAddressEdit = new AddressInfo();

        #endregion
        #region IEditableObject
        private bool isEditing = false;
    
    	protected override void BeginEditProtected(){
            if (!isEditing) 
            {
        		WSUserNameEdit = WSUserName;
        		WSPasswordEdit = WSPassword;
        		WSEnabledEdit = WSEnabled;
                isEditing = true;
            }
    	}
    
        protected virtual void CancelEditProtected(){
            WSUserName = WSUserNameEdit;
            WSPassword = WSPasswordEdit;
            WSEnabled = WSEnabledEdit;
            isEditing = false;
        }
    
    	protected virtual void EndEditProtected(){
    	    isEditing = false;
        }
            

        #endregion
        #region Equality Operators
        public override bool Equals (object obj)
        {
            if (!(obj is Customer))
                return false;
                    
            Customer o = (Customer)obj;
            return (1==1
              && this.CompanyId == o.CompanyId 
            );
        }
    
        public override int GetHashCode()
        {
            return (1
              ^ this.CompanyId.GetHashCode()
            );
        }

        #endregion
    }
}
