//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Objects.DataClasses;
using System.Collections.Generic;

namespace OrderIT.ModelIA
{
    public partial class OrderITEntitiesIA : ObjectContext
    {
        public const string ConnectionString = "name=OrderITEntitiesIA";
        public const string ContainerName = "OrderITEntitiesIA";
    
        #region Constructors
    
        public OrderITEntitiesIA()
            : base(ConnectionString, ContainerName)
        {
        }
    
        public OrderITEntitiesIA(string connectionString)
            : base(connectionString, ContainerName)
        {
        }
    
        public OrderITEntitiesIA(EntityConnection connection)
            : base(connection, ContainerName)
        {
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Company> Companies
        {
            get { return _companies  ?? (_companies = CreateObjectSet<Company>("Companies")); }
        }
        private ObjectSet<Company> _companies;
    
        public ObjectSet<Order> Orders
        {
            get { return _orders  ?? (_orders = CreateObjectSet<Order>("Orders")); }
        }
        private ObjectSet<Order> _orders;
    
        public ObjectSet<OrderDetail> OrderDetails
        {
            get { return _orderDetails  ?? (_orderDetails = CreateObjectSet<OrderDetail>("OrderDetails")); }
        }
        private ObjectSet<OrderDetail> _orderDetails;
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;

        #endregion
    }
}
