//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using OrderIT.Model.Notifications;


namespace OrderIT.Model
{
    public partial class AddressInfo
    {
        #region Primitive Properties
    
        public string Address
        {
            get;
            set;
        }
    
        public string City
        {
            get;
            set;
        }
    
        public string ZipCode
        {
            get;
            set;
        }
    
        public string Country
        {
            get;
            set;
        }

        #endregion
    }
}
