//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using OrderIT.Model.Notifications;


namespace OrderIT.Model
{
    [DataContract(IsReference = true)]
    public partial class GeometrySample  : INotifyPropertyChanged, IEditableObject
    {
        #region INotifyPropertyChanged
    		public event PropertyChangedEventHandler PropertyChanged;
    
    		protected void NotifyPropertyChanged(String info) {
    			if (PropertyChanged != null) {
    				PropertyChanged(this, new PropertyChangedEventArgs(info));
    			}
    		}

        #endregion
        #region Primitive Properties
    	
        [DataMember]
        public virtual int Id
        {
            get { return _id; }
            set { _id = value; NotifyPropertyChanged("Id"); }
        }
        private int _id;
        protected int IdEdit { get; set; }
    	
        [DataMember]
        public virtual byte[] SpatialData
        {
            get { return _spatialData; }
            set { _spatialData = value; NotifyPropertyChanged("SpatialData"); }
        }
        private byte[] _spatialData;
        protected byte[] SpatialDataEdit { get; set; }

        #endregion
        #region IEditableObject
    
        void IEditableObject.BeginEdit(){
    	    BeginEditProtected();
        }
    
        void IEditableObject.EndEdit(){
    	    EndEditProtected();
    	}
    
        void IEditableObject.CancelEdit(){
    	    CancelEditProtected();
        }
    	
        private bool isEditing = false;
    
    	protected virtual void BeginEditProtected(){
            if (!isEditing) 
            {
        		IdEdit = Id;
        		SpatialDataEdit = SpatialData;
                isEditing = true;
            }
    	}
    
        protected virtual void CancelEditProtected(){
            Id = IdEdit;
            SpatialData = SpatialDataEdit;
            isEditing = false;
        }
    
    	protected virtual void EndEditProtected(){
    	    isEditing = false;
        }
            

        #endregion
        #region Equality Operators
        public override bool Equals (object obj)
        {
            if (!this.GetType().IsInstanceOfType(obj) && !obj.GetType().IsInstanceOfType(this))
                return false;
                    
            GeometrySample o = (GeometrySample)obj;
            return (1==1
              && this.Id == o.Id 
            );
        }
    
        public override int GetHashCode()
        {
            return (1
              ^ this.Id.GetHashCode()
            );
        }

        #endregion
    }
}
